workflows:
  android-build:
    name: Android Build
    environment:
      java: 11
    scripts:
      - name: Set Gradle permissions
        script: chmod +x ./gradlew
      - name: Clean Project
        script: ./gradlew clean
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
