workflows:
  build-android-app:
    name: Build KidsDragDropAPK
    max_build_duration: 60
    environment:
      java: 17

    scripts:
      - name: Generate Gradle wrapper
        script: gradle wrapper
      - name: Make Gradlew executable
        script: chmod +x ./gradlew

      - name: Build Debug APK
        script: ./gradlew assembleDebug --stacktrace --no-daemon

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
